// src/screens/Home/styles.ts
import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const BANNER_W = SCREEN_W - 32;
const CARD_W = (SCREEN_W - 48) / 2;

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f7f8fa' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, backgroundColor: '#fff' },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  locationPin: { fontSize: 12 },
  locationText: { fontSize: 14, fontWeight: '800', color: '#111' },
  locationChevron: { fontSize: 10, color: '#6b7280' },
  greeting: { fontSize: 11, color: '#6b7280', marginTop: 2 },
  headerActions: { flexDirection: 'row', gap: 8 },
  iconWrap: { position: 'relative', padding: 6 },
  iconTxt: { fontSize: 22 },
  badge: { position: 'absolute', top: 2, right: 2, backgroundColor: '#ef4444', borderRadius: 999, width: 16, height: 16, alignItems: 'center', justifyContent: 'center' },
  badgeTxt: { fontSize: 9, color: '#fff', fontWeight: '800' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', marginHorizontal: 16, marginVertical: 10, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  searchIcon: { fontSize: 16, marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: '#111' },
  filterBtn: { backgroundColor: '#f3f4f6', borderRadius: 10, padding: 6 },
  filterTxt: { fontSize: 14 },
  bannerCard: { width: BANNER_W, height: 160, borderRadius: 20, overflow: 'hidden', marginRight: 8 },
  bannerImg: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  bannerOverlay: { ...StyleSheet.absoluteFillObject, flexDirection: 'row', alignItems: 'center', padding: 20 },
  bannerEmoji: { fontSize: 48, marginRight: 16 },
  bannerTitle: { fontSize: 18, fontWeight: '900', color: '#fff' },
  bannerSub: { fontSize: 12, color: 'rgba(255,255,255,0.85)', marginTop: 4 },
  bannerCta: { backgroundColor: 'rgba(255,255,255,0.2)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, marginTop: 10, alignSelf: 'flex-start' },
  bannerCtaTxt: { color: '#fff', fontSize: 12, fontWeight: '800' },
  dotsRow: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginTop: 10 },
  dot: { width: 6, height: 6, borderRadius: 999, backgroundColor: '#d1d5db' },
  dotActive: { width: 20, backgroundColor: '#059669' },
  section: { marginTop: 16, paddingHorizontal: 16 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '900', color: '#111' },
  seeAll: { fontSize: 12, fontWeight: '700', color: '#059669' },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: '#f3f4f6', marginRight: 8 },
  chipActive: { backgroundColor: '#111' },
  chipIcon: { fontSize: 14 },
  chipTxt: { fontSize: 12, fontWeight: '700', color: '#374151' },
  chipTxtActive: { color: '#fff' },
  dealCard: { width: 150, backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', marginRight: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  dealBadge: { position: 'absolute', top: 8, left: 8, backgroundColor: '#ef4444', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, zIndex: 10 },
  dealBadgeTxt: { color: '#fff', fontSize: 10, fontWeight: '900' },
  dealImg: { width: '100%', height: 110 },
  dealInfo: { padding: 10 },
  dealName: { fontSize: 12, fontWeight: '800', color: '#111', lineHeight: 16 },
  dealStore: { fontSize: 10, color: '#9ca3af', marginTop: 2 },
  dealPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  dealOriginal: { fontSize: 10, color: '#9ca3af', textDecorationLine: 'line-through' },
  dealPrice: { fontSize: 14, fontWeight: '900', color: '#059669' },
  soldRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  soldBar: { flex: 1, height: 4, backgroundColor: '#f3f4f6', borderRadius: 999 },
  soldFill: { height: '100%', backgroundColor: '#f97316', borderRadius: 999 },
  soldTxt: { fontSize: 9, color: '#9ca3af' },
  addDealBtn: { backgroundColor: '#059669', borderRadius: 8, paddingVertical: 6, alignItems: 'center', marginTop: 8 },
  addDealTxt: { color: '#fff', fontSize: 11, fontWeight: '800' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 8 },
  trendCard: { width: CARD_W, backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  trendImg: { width: '100%', height: 140 },
  favBtn: { position: 'absolute', top: 8, right: 8, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 999, width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  trendTag: { position: 'absolute', bottom: 8, left: 8, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  trendTagTxt: { fontSize: 9, fontWeight: '800' },
  trendInfo: { padding: 10 },
  trendName: { fontSize: 12, fontWeight: '800', color: '#111' },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 4 },
  ratingTxt: { fontSize: 11, fontWeight: '800', color: '#111' },
  reviewsTxt: { fontSize: 10, color: '#9ca3af' },
  trendBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  trendPrice: { fontSize: 14, fontWeight: '900', color: '#059669' },
  addBtn: { width: 28, height: 28, backgroundColor: '#111', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  addBtnTxt: { color: '#fff', fontSize: 18, fontWeight: '900', lineHeight: 22 },
  nearbyCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 20, padding: 12, marginBottom: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  nearbyImg: { width: 64, height: 64, borderRadius: 16, marginRight: 12 },
  nearbyHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2 },
  nearbyName: { fontSize: 13, fontWeight: '900', color: '#111', flex: 1 },
  openBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 999 },
  closedBadge: { backgroundColor: '#fee2e2' },
  openTxt: { fontSize: 10, fontWeight: '700', color: '#16a34a' },
  closedTxt: { color: '#dc2626' },
  nearbyCat: { fontSize: 11, color: '#9ca3af', marginBottom: 4 },
  nearbyMeta: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  nearbyMetaTxt: { fontSize: 11, color: '#6b7280' },
  nearbyDot: { fontSize: 10, color: '#d1d5db' },
});