// src/screens/Explorador/styles.ts
import { Dimensions, StyleSheet } from 'react-native';

const { width: W } = Dimensions.get('window');

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f7f8fa' },
  header: { paddingHorizontal: 16, paddingVertical: 12, backgroundColor: '#fff' },
  headerTitle: { fontSize: 22, fontWeight: '900', color: '#111' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', marginHorizontal: 16, marginVertical: 10, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  searchInput: { flex: 1, fontSize: 14, color: '#111' },
  tabRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 8 },
  tab: { flex: 1, paddingVertical: 8, borderRadius: 12, backgroundColor: '#f3f4f6', alignItems: 'center' },
  tabActive: { backgroundColor: '#059669' },
  tabTxt: { fontSize: 11, fontWeight: '700', color: '#6b7280' },
  tabTxtActive: { color: '#fff' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 8 },
  catCard: { width: (W - 44) / 2, borderRadius: 20, padding: 16, borderWidth: 1.5, alignItems: 'flex-start' },
  catIcon: { fontSize: 32, marginBottom: 8 },
  catName: { fontSize: 14, fontWeight: '900', color: '#111' },
  catCount: { fontSize: 11, color: '#6b7280', marginTop: 2 },
  sectionTitle: { fontSize: 16, fontWeight: '900', color: '#111', marginBottom: 4 },
  projectCard: { backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  projectImg: { width: '100%', height: 120 },
  projectInfo: { padding: 14 },
  projectName: { fontSize: 15, fontWeight: '900', color: '#111' },
  projectAuthor: { fontSize: 12, color: '#9ca3af', marginTop: 2, marginBottom: 10 },
  progressBar: { height: 8, backgroundColor: '#f3f4f6', borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#059669', borderRadius: 999 },
  projectMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  projectRaised: { fontSize: 12, color: '#059669', fontWeight: '700' },
  projectPct: { fontSize: 12, fontWeight: '900', color: '#111' },
  projectFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  returnBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  returnTxt: { color: '#059669', fontSize: 12, fontWeight: '700' },
  investBtn: { backgroundColor: '#059669', paddingHorizontal: 20, paddingVertical: 8, borderRadius: 12 },
  investTxt: { color: '#fff', fontSize: 13, fontWeight: '900' },
  courseCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 16, padding: 14, gap: 12 },
  courseIcon: { fontSize: 32 },
  courseTitle: { fontSize: 14, fontWeight: '800', color: '#111' },
  courseMeta: { fontSize: 11, color: '#6b7280', marginTop: 2 },
  startBtn: { backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  startTxt: { fontSize: 12, fontWeight: '800', color: '#059669' },
});