// src/screens/EditarPerfil/styles.ts
import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f7f8fa' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  headerBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerBtnRight: { minWidth: 64, height: 40, alignItems: 'flex-end', justifyContent: 'center', paddingRight: 4 },
  headerBtnTxt: { fontSize: 28, color: '#111', lineHeight: 28 },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '800', color: '#111' },
  saveTxt: { fontSize: 15, fontWeight: '800', color: '#059669' },
  saveTxtDisabled: { color: '#9ca3af' },

  scroll: { padding: 16, paddingBottom: 40 },

  avatarWrap: { alignItems: 'center', paddingVertical: 12, marginBottom: 16 },
  avatar: {
    width: 110, height: 110, borderRadius: 999,
    borderWidth: 3, borderColor: '#059669', backgroundColor: '#e5e7eb',
  },
  avatarEditBadge: {
    position: 'absolute', bottom: 2, right: 2,
    backgroundColor: '#059669', width: 32, height: 32, borderRadius: 999,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 3, borderColor: '#f7f8fa',
  },
  avatarEditBadgeTxt: { fontSize: 14 },
  cambiarFotoLink: { marginTop: 14, fontSize: 14, fontWeight: '800', color: '#059669', textAlign: 'center' },
  pendingHint: {
    marginTop: 10,
    fontSize: 11,
    color: '#92400e',
    backgroundColor: '#fef3c7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontWeight: '700',
    overflow: 'hidden',
  },

  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  cardTitle: { fontSize: 13, fontWeight: '900', color: '#111', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.4 },
  label: { fontSize: 12, fontWeight: '800', color: '#6b7280', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.4 },

  inputWrap: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#f3f4f6', borderRadius: 14,
    paddingHorizontal: 14, height: 50, gap: 10,
  },
  inputIcon: { fontSize: 16 },
  input: { flex: 1, fontSize: 15, color: '#111' },
  hint: { fontSize: 11, color: '#9ca3af', marginTop: 6, marginLeft: 4 },

  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  linkRowPressed: { backgroundColor: '#ecfdf5' },
  linkIcon:    { fontSize: 18 },
  linkLabel:   { fontSize: 14, fontWeight: '800', color: '#111' },
  linkSub:     { fontSize: 11, color: '#9ca3af', marginTop: 2 },
  linkChevron: { fontSize: 22, color: '#d1d5db' },

  btn: {
    backgroundColor: '#059669',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  btnPressed:  { backgroundColor: '#047857', transform: [{ scale: 0.98 }] },
  btnDisabled: { backgroundColor: '#a7f3d0', shadowOpacity: 0, elevation: 0 },
  btnTxt: { color: '#fff', fontSize: 15, fontWeight: '900' },

  // ---------- MODAL personalizado para foto ----------
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 8,
    paddingHorizontal: 16,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d1d5db',
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
    marginBottom: 12,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
    gap: 12,
  },
  modalOptionPressed: { backgroundColor: '#ecfdf5' },
  modalOptionIcon:    { fontSize: 22 },
  modalOptionTxt:     { fontSize: 15, fontWeight: '700', color: '#111' },

  modalCancel: {
    backgroundColor: '#fee2e2',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  modalCancelPressed: { backgroundColor: '#fecaca' },
  modalCancelTxt:     { color: '#ef4444', fontWeight: '900', fontSize: 15 },
});
