// src/screens/Profile/ProfileStyles.ts
import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f7f8fa' },
  profileHeader: { backgroundColor: '#fff', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 24, marginBottom: 12 },
  avatarContainer: { position: 'relative', marginBottom: 12 },
  avatar: { width: 90, height: 90, borderRadius: 999, borderWidth: 3, borderColor: '#059669' },
  editAvatarBtn: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#fff', borderRadius: 999, padding: 4, borderWidth: 1, borderColor: '#e5e7eb' },
  name: { fontSize: 22, fontWeight: '900', color: '#111' },
  handle: { fontSize: 13, color: '#9ca3af', marginTop: 2, marginBottom: 16 },
  statsRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  stat: { flex: 1, alignItems: 'center' },
  statNum: { fontSize: 18, fontWeight: '900', color: '#111' },
  statLabel: { fontSize: 11, color: '#9ca3af', marginTop: 2 },
  statDivider: { width: 1, height: 30, backgroundColor: '#e5e7eb' },
  actionRow: { flexDirection: 'row', gap: 12 },
  editBtn: { flex: 1, backgroundColor: '#111', paddingVertical: 10, borderRadius: 14, alignItems: 'center' },
  editBtnTxt: { color: '#fff', fontWeight: '800', fontSize: 13 },
  shareBtn: { backgroundColor: '#f3f4f6', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 14, alignItems: 'center' },
  shareBtnTxt: { color: '#111', fontWeight: '800', fontSize: 13 },
  walletCard: { backgroundColor: '#059669', marginHorizontal: 16, marginBottom: 12, borderRadius: 20, padding: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  walletLabel: { color: 'rgba(255,255,255,0.8)', fontSize: 12, marginBottom: 4 },
  walletBalance: { color: '#fff', fontSize: 28, fontWeight: '900' },
  walletSub: { color: 'rgba(255,255,255,0.7)', fontSize: 11, marginTop: 2 },
  walletActions: { gap: 8 },
  walletBtn: { backgroundColor: '#fff', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12, alignItems: 'center' },
  walletBtnOut: { backgroundColor: 'rgba(255,255,255,0.15)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)' },
  walletBtnTxt: { color: '#059669', fontWeight: '800', fontSize: 12 },
  tabRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 4 },
  tab: { flex: 1, paddingVertical: 8, borderRadius: 12, backgroundColor: '#f3f4f6', alignItems: 'center' },
  tabActive: { backgroundColor: '#059669' },
  tabTxt: { fontSize: 11, fontWeight: '700', color: '#6b7280' },
  tabTxtActive: { color: '#fff' },
  orderCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, padding: 12, gap: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 1 },
  orderImg: { width: 56, height: 56, borderRadius: 12 },
  orderStore: { fontSize: 13, fontWeight: '800', color: '#111' },
  orderProduct: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  orderDate: { fontSize: 11, color: '#9ca3af', marginTop: 2 },
  orderPrice: { fontSize: 14, fontWeight: '900', color: '#059669' },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statusTxt: { fontSize: 10, fontWeight: '800' },
  reorderBtn: { backgroundColor: '#f0fdf4', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  reorderTxt: { fontSize: 10, color: '#059669', fontWeight: '700' },
  exploreBtn: { backgroundColor: '#059669', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 14, marginTop: 20 },
  exploreBtnTxt: { color: '#fff', fontWeight: '800' },
  settingRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, padding: 14, gap: 12 },
  settingIcon: { fontSize: 20 },
  settingLabel: { flex: 1, fontSize: 14, fontWeight: '700', color: '#111' },
  settingSub: { fontSize: 11, color: '#9ca3af', marginTop: 1 },
  logoutBtn: { backgroundColor: '#fee2e2', borderRadius: 16, padding: 14, alignItems: 'center', marginTop: 8 },
  logoutTxt: { color: '#ef4444', fontWeight: '800', fontSize: 14 },
});