import {
  AvocadoIcon,
  BabyIcon,
  BabyCarriageIcon,
  BalloonIcon,
  BarbellIcon,
  BasketIcon,
  BedIcon,
  BeerSteinIcon,
  BicycleIcon,
  BookIcon,
  BreadIcon,
  BowlFoodIcon,
  BowlSteamIcon,
  CakeIcon,
  CameraIcon,
  CarIcon,
  CarProfileIcon,
  CarrotIcon,
  ClipboardIcon,
  CoffeeIcon,
  ConfettiIcon,
  CookieIcon,
  CookingPotIcon,
  CouchIcon,
  CrossIcon,
  DeviceMobileIcon,
  DeviceMobileCameraIcon,
  DiamondIcon,
  DressIcon,
  DropIcon,
  EggIcon,
  EggCrackIcon,
  EnvelopeIcon,
  EyeglassesIcon,
  FireIcon,
  FirstAidIcon,
  FirstAidKitIcon,
  FishIcon,
  FishSimpleIcon,
  FlameIcon,
  FlowerIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  GuitarIcon,
  HamburgerIcon,
  HandSoapIcon,
  HandbagIcon,
  HandsPrayingIcon,
  HardHatIcon,
  HeadphonesIcon,
  HeartIcon,
  HeartbeatIcon,
  IceCreamIcon,
  KeyIcon,
  LaptopIcon,
  LeafIcon,
  LightningIcon,
  MotorcycleIcon,
  NotePencilIcon,
  OrangeSliceIcon,
  PackageIcon,
  PaintBrushIcon,
  PaintRollerIcon,
  PaletteIcon,
  PawPrintIcon,
  PencilIcon,
  PillIcon,
  PizzaIcon,
  PlantIcon,
  PlugIcon,
  PlugsIcon,
  PopcornIcon,
  PottedPlantIcon,
  PuzzlePieceIcon,
  RecycleIcon,
  ScissorsIcon,
  ShirtFoldedIcon,
  SneakerIcon,
  SoccerBallIcon,
  SparkleIcon,
  SprayBottleIcon,
  StorefrontIcon,
  SunglassesIcon,
  TShirtIcon,
  TeaBagIcon,
  TicketIcon,
  TireIcon,
  ToolboxIcon,
  ToothIcon,
  TruckIcon,
  UsersThreeIcon,
  WashingMachineIcon,
  WheelchairIcon,
  WineIcon,
  WrenchIcon,
  type IconProps,
} from "phosphor-react-native";
import type { ComponentType } from "react";

export const CATEGORIAS = [
  "comida",
  "mercado",
  "farmacia",
  "bebidas",
  "panaderia",
  "postres",
  "frutas",
  "verduras",
  "ropa",
  "calzado",
  "electronica",
  "hogar",
  "envios",
  "general",
  "comida_rapida",
  "restaurantes",
  "comida_saludable",
  "vegana",
  "comida_tipica",
  "pizza",
  "sushi",
  "mexicana",
  "italiana",
  "pollo",
  "mariscos",
  "parrilla",
  "desayunos",
  "almuerzos",
  "catering",
  "dieta_especial",
  "cafe",
  "jugos",
  "cerveceria",
  "vinos",
  "energeticas",
  "te",
  "agua_refrescos",
  "reposteria",
  "heladeria",
  "chocolateria",
  "dulces_tipicos",
  "snacks",
  "carniceria",
  "pescaderia",
  "organicos",
  "granel",
  "lacteos",
  "huevos",
  "especias",
  "optica",
  "dental",
  "suplementos",
  "equipo_medico",
  "adulto_mayor",
  "primeros_auxilios",
  "cosmeticos",
  "cuidado_piel",
  "peluqueria",
  "perfumeria",
  "higiene",
  "barberia",
  "unas",
  "ropa_mujer",
  "ropa_hombre",
  "ropa_infantil",
  "ropa_deportiva",
  "lenceria",
  "uniformes",
  "accesorios",
  "joyeria",
  "lentes_sol",
  "muebles",
  "decoracion",
  "electrodomesticos",
  "electro_pequeno",
  "blancos",
  "cocina",
  "ferreteria",
  "pintura",
  "jardineria",
  "limpieza",
  "celulares",
  "computadoras",
  "videojuegos",
  "audio",
  "camaras",
  "domotica",
  "bebes",
  "juguetes",
  "escolar_ninos",
  "sillas_auto",
  "mascotas",
  "veterinaria",
  "peluqueria_canina",
  "papeleria",
  "libreria",
  "oficina",
  "impresiones",
  "deportes",
  "suple_deportivo",
  "bicicletas",
  "gimnasio",
  "repuestos",
  "accesorios_auto",
  "lubricantes",
  "llantas",
  "lavado_autos",
  "motos",
  "flores",
  "regalos",
  "pinateria",
  "globos",
  "tarjetas",
  "peluches",
  "construccion",
  "herramientas",
  "electricidad_plomeria",
  "instrumentos",
  "manualidades",
  "fotografia",
  "entretenimiento",
  "lavanderia",
  "mudanzas",
  "reparaciones",
  "cerrajeria",
  "segunda_mano",
  "importados",
  "religiosos",
  "souvenirs",
] as const;
export type Categoria = (typeof CATEGORIAS)[number];

export const CATEGORIA_LABEL: Record<Categoria, string> = {
  comida: "Comida",
  mercado: "Mercado",
  farmacia: "Farmacia",
  bebidas: "Bebidas",
  panaderia: "Panadería",
  postres: "Postres",
  frutas: "Frutas",
  verduras: "Verduras",
  ropa: "Ropa",
  calzado: "Calzado",
  electronica: "Electrónica",
  hogar: "Hogar",
  envios: "Envíos",
  general: "General",
  comida_rapida: "Comida rápida",
  restaurantes: "Restaurantes",
  comida_saludable: "Comida saludable",
  vegana: "Vegana/vegetariana",
  comida_tipica: "Comida típica",
  pizza: "Pizza",
  sushi: "Sushi/asiática",
  mexicana: "Comida mexicana",
  italiana: "Comida italiana",
  pollo: "Pollo/rostizados",
  mariscos: "Mariscos",
  parrilla: "Parrilladas/carnes",
  desayunos: "Desayunos",
  almuerzos: "Almuerzos ejecutivos",
  catering: "Catering/eventos",
  dieta_especial: "Dietas especiales",
  cafe: "Café",
  jugos: "Jugos naturales",
  cerveceria: "Cervecería",
  vinos: "Vinos y licores",
  energeticas: "Bebidas energéticas",
  te: "Té/infusiones",
  agua_refrescos: "Agua y refrescos",
  reposteria: "Repostería/pasteles",
  heladeria: "Heladería",
  chocolateria: "Chocolatería",
  dulces_tipicos: "Dulces típicos",
  snacks: "Snacks/botanas",
  carniceria: "Carnicería",
  pescaderia: "Pescadería",
  organicos: "Productos orgánicos",
  granel: "Productos a granel",
  lacteos: "Lácteos",
  huevos: "Huevos",
  especias: "Especias y condimentos",
  optica: "Óptica",
  dental: "Dental",
  suplementos: "Suplementos/vitaminas",
  equipo_medico: "Equipo médico",
  adulto_mayor: "Adultos mayores",
  primeros_auxilios: "Primeros auxilios",
  cosmeticos: "Cosméticos/maquillaje",
  cuidado_piel: "Cuidado de la piel",
  peluqueria: "Peluquería",
  perfumeria: "Perfumería",
  higiene: "Higiene personal",
  barberia: "Barbería",
  unas: "Uñas/manicure",
  ropa_mujer: "Ropa de mujer",
  ropa_hombre: "Ropa de hombre",
  ropa_infantil: "Ropa infantil",
  ropa_deportiva: "Ropa deportiva",
  lenceria: "Ropa íntima",
  uniformes: "Uniformes",
  accesorios: "Accesorios",
  joyeria: "Joyería y relojes",
  lentes_sol: "Lentes de sol",
  muebles: "Muebles",
  decoracion: "Decoración",
  electrodomesticos: "Electrodomésticos",
  electro_pequeno: "Electrodomésticos pequeños",
  blancos: "Blancos (sábanas/toallas)",
  cocina: "Cocina y utensilios",
  ferreteria: "Ferretería",
  pintura: "Pintura",
  jardineria: "Jardinería/plantas",
  limpieza: "Productos de limpieza",
  celulares: "Celulares y accesorios",
  computadoras: "Computadoras/laptops",
  videojuegos: "Videojuegos",
  audio: "Audio/parlantes",
  camaras: "Cámaras",
  domotica: "Domótica",
  bebes: "Artículos para bebé",
  juguetes: "Juguetes",
  escolar_ninos: "Escolares",
  sillas_auto: "Coches/sillas de carro",
  mascotas: "Mascotas",
  veterinaria: "Veterinaria",
  peluqueria_canina: "Peluquería canina",
  papeleria: "Papelería/útiles",
  libreria: "Librería/libros",
  oficina: "Material de oficina",
  impresiones: "Impresiones/copias",
  deportes: "Artículos deportivos",
  suple_deportivo: "Suplementos deportivos",
  bicicletas: "Bicicletas",
  gimnasio: "Equipo de gimnasio",
  repuestos: "Repuestos",
  accesorios_auto: "Accesorios para vehículos",
  lubricantes: "Lubricantes",
  llantas: "Llantas",
  lavado_autos: "Lavado de autos",
  motos: "Motocicletas",
  flores: "Flores/florería",
  regalos: "Regalos",
  pinateria: "Piñatería/fiesta",
  globos: "Globos",
  tarjetas: "Tarjetas y envoltorios",
  peluches: "Peluches",
  construccion: "Materiales de construcción",
  herramientas: "Herramientas",
  electricidad_plomeria: "Electricidad/plomería",
  instrumentos: "Instrumentos musicales",
  manualidades: "Arte/manualidades",
  fotografia: "Fotografía",
  entretenimiento: "Boletos/entretenimiento",
  lavanderia: "Lavandería",
  mudanzas: "Mudanzas",
  reparaciones: "Reparaciones a domicilio",
  cerrajeria: "Cerrajería",
  segunda_mano: "Segunda mano/usado",
  importados: "Importados",
  religiosos: "Artículos religiosos",
  souvenirs: "Souvenirs/artesanías",
};

export const CATEGORIA_ICON: Record<Categoria, ComponentType<IconProps>> = {
  comida: ForkKnifeIcon,
  mercado: BasketIcon,
  farmacia: PillIcon,
  bebidas: CoffeeIcon,
  panaderia: BreadIcon,
  postres: IceCreamIcon,
  frutas: LeafIcon,
  verduras: CarrotIcon,
  ropa: TShirtIcon,
  calzado: SneakerIcon,
  electronica: DeviceMobileIcon,
  hogar: CouchIcon,
  envios: TruckIcon,
  general: PackageIcon,
  comida_rapida: HamburgerIcon,
  restaurantes: StorefrontIcon,
  comida_saludable: AvocadoIcon,
  vegana: PlantIcon,
  comida_tipica: BowlFoodIcon,
  pizza: PizzaIcon,
  sushi: FishSimpleIcon,
  mexicana: CookingPotIcon,
  italiana: BowlSteamIcon,
  pollo: FireIcon,
  mariscos: FishIcon,
  parrilla: FlameIcon,
  desayunos: EggIcon,
  almuerzos: PackageIcon,
  catering: UsersThreeIcon,
  dieta_especial: HeartbeatIcon,
  cafe: CoffeeIcon,
  jugos: OrangeSliceIcon,
  cerveceria: BeerSteinIcon,
  vinos: WineIcon,
  energeticas: LightningIcon,
  te: TeaBagIcon,
  agua_refrescos: DropIcon,
  reposteria: CakeIcon,
  heladeria: IceCreamIcon,
  chocolateria: CookieIcon,
  dulces_tipicos: CookieIcon,
  snacks: PopcornIcon,
  carniceria: FireIcon,
  pescaderia: FishIcon,
  organicos: PlantIcon,
  granel: BasketIcon,
  lacteos: DropIcon,
  huevos: EggCrackIcon,
  especias: FireIcon,
  optica: EyeglassesIcon,
  dental: ToothIcon,
  suplementos: PillIcon,
  equipo_medico: FirstAidKitIcon,
  adulto_mayor: WheelchairIcon,
  primeros_auxilios: FirstAidIcon,
  cosmeticos: SparkleIcon,
  cuidado_piel: DropIcon,
  peluqueria: ScissorsIcon,
  perfumeria: FlowerIcon,
  higiene: HandSoapIcon,
  barberia: ScissorsIcon,
  unas: SparkleIcon,
  ropa_mujer: DressIcon,
  ropa_hombre: TShirtIcon,
  ropa_infantil: BabyIcon,
  ropa_deportiva: BarbellIcon,
  lenceria: HeartIcon,
  uniformes: ShirtFoldedIcon,
  accesorios: HandbagIcon,
  joyeria: DiamondIcon,
  lentes_sol: SunglassesIcon,
  muebles: CouchIcon,
  decoracion: PaletteIcon,
  electrodomesticos: WashingMachineIcon,
  electro_pequeno: PlugIcon,
  blancos: BedIcon,
  cocina: CookingPotIcon,
  ferreteria: WrenchIcon,
  pintura: PaintRollerIcon,
  jardineria: PottedPlantIcon,
  limpieza: SprayBottleIcon,
  celulares: DeviceMobileCameraIcon,
  computadoras: LaptopIcon,
  videojuegos: GameControllerIcon,
  audio: HeadphonesIcon,
  camaras: CameraIcon,
  domotica: PlugsIcon,
  bebes: BabyIcon,
  juguetes: PuzzlePieceIcon,
  escolar_ninos: GraduationCapIcon,
  sillas_auto: BabyCarriageIcon,
  mascotas: PawPrintIcon,
  veterinaria: CrossIcon,
  peluqueria_canina: ScissorsIcon,
  papeleria: PencilIcon,
  libreria: BookIcon,
  oficina: ClipboardIcon,
  impresiones: NotePencilIcon,
  deportes: SoccerBallIcon,
  suple_deportivo: BarbellIcon,
  bicicletas: BicycleIcon,
  gimnasio: BarbellIcon,
  repuestos: CarProfileIcon,
  accesorios_auto: CarIcon,
  lubricantes: DropIcon,
  llantas: TireIcon,
  lavado_autos: SprayBottleIcon,
  motos: MotorcycleIcon,
  flores: FlowerIcon,
  regalos: GiftIcon,
  pinateria: ConfettiIcon,
  globos: BalloonIcon,
  tarjetas: EnvelopeIcon,
  peluches: PuzzlePieceIcon,
  construccion: HardHatIcon,
  herramientas: ToolboxIcon,
  electricidad_plomeria: PlugIcon,
  instrumentos: GuitarIcon,
  manualidades: PaintBrushIcon,
  fotografia: CameraIcon,
  entretenimiento: TicketIcon,
  lavanderia: WashingMachineIcon,
  mudanzas: TruckIcon,
  reparaciones: WrenchIcon,
  cerrajeria: KeyIcon,
  segunda_mano: RecycleIcon,
  importados: GlobeIcon,
  religiosos: HandsPrayingIcon,
  souvenirs: PackageIcon,
};

/** One accent hue per category so the category rail isn't monochrome (mirrors web). */
export const CATEGORIA_COLOR: Record<Categoria, string> = {
  comida: "#f97316",
  mercado: "#10b981",
  farmacia: "#14b8a6",
  bebidas: "#3b82f6",
  panaderia: "#d97706",
  postres: "#ec4899",
  frutas: "#84cc16",
  verduras: "#15803d",
  ropa: "#7c3aed",
  calzado: "#0891b2",
  electronica: "#475569",
  hogar: "#b45309",
  envios: "#6366f1",
  general: "#64748b",
  comida_rapida: "#ea580c",
  restaurantes: "#b91c1c",
  comida_saludable: "#16a34a",
  vegana: "#15803d",
  comida_tipica: "#b45309",
  pizza: "#dc2626",
  sushi: "#db2777",
  mexicana: "#ea580c",
  italiana: "#ca8a04",
  pollo: "#d97706",
  mariscos: "#0891b2",
  parrilla: "#dc2626",
  desayunos: "#f59e0b",
  almuerzos: "#78716c",
  catering: "#7c3aed",
  dieta_especial: "#059669",
  cafe: "#78350f",
  jugos: "#f97316",
  cerveceria: "#ca8a04",
  vinos: "#7c2d12",
  energeticas: "#eab308",
  te: "#65a30d",
  agua_refrescos: "#0ea5e9",
  reposteria: "#ec4899",
  heladeria: "#38bdf8",
  chocolateria: "#78350f",
  dulces_tipicos: "#f472b6",
  snacks: "#eab308",
  carniceria: "#b91c1c",
  pescaderia: "#0284c7",
  organicos: "#22c55e",
  granel: "#a16207",
  lacteos: "#64748b",
  huevos: "#ca8a04",
  especias: "#dc2626",
  optica: "#0891b2",
  dental: "#06b6d4",
  suplementos: "#16a34a",
  equipo_medico: "#dc2626",
  adulto_mayor: "#6366f1",
  primeros_auxilios: "#ef4444",
  cosmeticos: "#ec4899",
  cuidado_piel: "#f472b6",
  peluqueria: "#a855f7",
  perfumeria: "#d946ef",
  higiene: "#06b6d4",
  barberia: "#1e293b",
  unas: "#f43f5e",
  ropa_mujer: "#db2777",
  ropa_hombre: "#2563eb",
  ropa_infantil: "#f59e0b",
  ropa_deportiva: "#16a34a",
  lenceria: "#f43f5e",
  uniformes: "#475569",
  accesorios: "#a16207",
  joyeria: "#eab308",
  lentes_sol: "#1e293b",
  muebles: "#92400e",
  decoracion: "#d946ef",
  electrodomesticos: "#64748b",
  electro_pequeno: "#0891b2",
  blancos: "#3b82f6",
  cocina: "#ea580c",
  ferreteria: "#52525b",
  pintura: "#dc2626",
  jardineria: "#16a34a",
  limpieza: "#06b6d4",
  celulares: "#2563eb",
  computadoras: "#1e293b",
  videojuegos: "#7c3aed",
  audio: "#ea580c",
  camaras: "#0f172a",
  domotica: "#eab308",
  bebes: "#ec4899",
  juguetes: "#f59e0b",
  escolar_ninos: "#2563eb",
  sillas_auto: "#16a34a",
  mascotas: "#a16207",
  veterinaria: "#dc2626",
  peluqueria_canina: "#0891b2",
  papeleria: "#2563eb",
  libreria: "#78350f",
  oficina: "#475569",
  impresiones: "#64748b",
  deportes: "#16a34a",
  suple_deportivo: "#dc2626",
  bicicletas: "#0891b2",
  gimnasio: "#7c3aed",
  repuestos: "#475569",
  accesorios_auto: "#1e293b",
  lubricantes: "#78350f",
  llantas: "#27272a",
  lavado_autos: "#0ea5e9",
  motos: "#dc2626",
  flores: "#ec4899",
  regalos: "#dc2626",
  pinateria: "#f59e0b",
  globos: "#a855f7",
  tarjetas: "#ec4899",
  peluches: "#f472b6",
  construccion: "#f59e0b",
  herramientas: "#52525b",
  electricidad_plomeria: "#eab308",
  instrumentos: "#7c2d12",
  manualidades: "#d946ef",
  fotografia: "#1e293b",
  entretenimiento: "#7c3aed",
  lavanderia: "#0891b2",
  mudanzas: "#78716c",
  reparaciones: "#ca8a04",
  cerrajeria: "#52525b",
  segunda_mano: "#16a34a",
  importados: "#2563eb",
  religiosos: "#a16207",
  souvenirs: "#ea580c",
};

export const CATEGORIA_EMOJI: Record<Categoria, string> = {
  comida: "🍔",
  mercado: "🛒",
  farmacia: "💊",
  bebidas: "🥤",
  panaderia: "🍞",
  postres: "🍰",
  frutas: "🍎",
  verduras: "🥕",
  ropa: "👕",
  calzado: "👟",
  electronica: "📱",
  hogar: "🛋️",
  envios: "🚚",
  general: "📦",
  comida_rapida: "🍔",
  restaurantes: "🍽️",
  comida_saludable: "🥑",
  vegana: "🌱",
  comida_tipica: "🫓",
  pizza: "🍕",
  sushi: "🍣",
  mexicana: "🌮",
  italiana: "🍝",
  pollo: "🍗",
  mariscos: "🦐",
  parrilla: "🥩",
  desayunos: "🍳",
  almuerzos: "🍱",
  catering: "🥂",
  dieta_especial: "💚",
  cafe: "☕",
  jugos: "🧃",
  cerveceria: "🍺",
  vinos: "🍷",
  energeticas: "⚡",
  te: "🍵",
  agua_refrescos: "🥤",
  reposteria: "🎂",
  heladeria: "🍦",
  chocolateria: "🍫",
  dulces_tipicos: "🍬",
  snacks: "🍿",
  carniceria: "🥩",
  pescaderia: "🐟",
  organicos: "🌿",
  granel: "🌾",
  lacteos: "🥛",
  huevos: "🥚",
  especias: "🌶️",
  optica: "👓",
  dental: "🦷",
  suplementos: "💊",
  equipo_medico: "🩺",
  adulto_mayor: "🧓",
  primeros_auxilios: "🚑",
  cosmeticos: "💄",
  cuidado_piel: "🧴",
  peluqueria: "💇",
  perfumeria: "🌸",
  higiene: "🧼",
  barberia: "💈",
  unas: "💅",
  ropa_mujer: "👗",
  ropa_hombre: "👔",
  ropa_infantil: "🧒",
  ropa_deportiva: "🎽",
  lenceria: "👙",
  uniformes: "🥼",
  accesorios: "👜",
  joyeria: "💍",
  lentes_sol: "🕶️",
  muebles: "🛋️",
  decoracion: "🖼️",
  electrodomesticos: "🧺",
  electro_pequeno: "🔌",
  blancos: "🛏️",
  cocina: "🍳",
  ferreteria: "🔧",
  pintura: "🎨",
  jardineria: "🪴",
  limpieza: "🧽",
  celulares: "📱",
  computadoras: "💻",
  videojuegos: "🎮",
  audio: "🎧",
  camaras: "📷",
  domotica: "💡",
  bebes: "👶",
  juguetes: "🧸",
  escolar_ninos: "🎒",
  sillas_auto: "🍼",
  mascotas: "🐾",
  veterinaria: "🐶",
  peluqueria_canina: "🐩",
  papeleria: "✏️",
  libreria: "📚",
  oficina: "🗂️",
  impresiones: "🖨️",
  deportes: "⚽",
  suple_deportivo: "🏋️",
  bicicletas: "🚲",
  gimnasio: "🏋️‍♂️",
  repuestos: "🔩",
  accesorios_auto: "🚗",
  lubricantes: "🛢️",
  llantas: "🛞",
  lavado_autos: "🚿",
  motos: "🏍️",
  flores: "💐",
  regalos: "🎁",
  pinateria: "🎉",
  globos: "🎈",
  tarjetas: "💌",
  peluches: "🧸",
  construccion: "🏗️",
  herramientas: "🧰",
  electricidad_plomeria: "⚡",
  instrumentos: "🎸",
  manualidades: "🖌️",
  fotografia: "📸",
  entretenimiento: "🎟️",
  lavanderia: "🧺",
  mudanzas: "🚚",
  reparaciones: "🛠️",
  cerrajeria: "🔑",
  segunda_mano: "♻️",
  importados: "🌎",
  religiosos: "🙏",
  souvenirs: "🎁",
};

export interface CategoriaGrupo {
  id: string;
  label: string;
  icon: ComponentType<IconProps>;
  color: string;
  emoji: string;
  categorias: Categoria[];
}

/**
 * Agrupa las 129 categorías en ~20 "familias" principales para la barra de Inicio y el
 * primer nivel de filtros de Explorar -- mirroring src/lib/categoryIcons.tsx (web).
 */
export const CATEGORIA_GRUPOS: CategoriaGrupo[] = [
  {
    id: "comida",
    label: "Comida",
    icon: ForkKnifeIcon,
    color: "#f97316",
    emoji: "🍔",
    categorias: ["comida", "comida_rapida", "restaurantes", "comida_saludable", "vegana", "comida_tipica", "pizza", "sushi", "mexicana", "italiana", "pollo", "mariscos", "parrilla", "desayunos", "almuerzos", "catering", "dieta_especial"],
  },
  {
    id: "mercado",
    label: "Mercado",
    icon: BasketIcon,
    color: "#10b981",
    emoji: "🛒",
    categorias: ["mercado", "carniceria", "pescaderia", "organicos", "granel", "lacteos", "huevos", "especias", "snacks"],
  },
  {
    id: "panaderia",
    label: "Panadería y postres",
    icon: BreadIcon,
    color: "#d97706",
    emoji: "🍞",
    categorias: ["panaderia", "postres", "reposteria", "heladeria", "chocolateria", "dulces_tipicos"],
  },
  {
    id: "frutas",
    label: "Frutas y verduras",
    icon: CarrotIcon,
    color: "#84cc16",
    emoji: "🍎",
    categorias: ["frutas", "verduras"],
  },
  {
    id: "bebidas",
    label: "Bebidas",
    icon: CoffeeIcon,
    color: "#3b82f6",
    emoji: "🥤",
    categorias: ["bebidas", "cafe", "jugos", "cerveceria", "vinos", "energeticas", "te", "agua_refrescos"],
  },
  {
    id: "farmacia",
    label: "Farmacia y salud",
    icon: PillIcon,
    color: "#14b8a6",
    emoji: "💊",
    categorias: ["farmacia", "optica", "dental", "suplementos", "equipo_medico", "adulto_mayor", "primeros_auxilios"],
  },
  {
    id: "belleza",
    label: "Belleza y cuidado",
    icon: SparkleIcon,
    color: "#ec4899",
    emoji: "💄",
    categorias: ["cosmeticos", "cuidado_piel", "peluqueria", "perfumeria", "higiene", "barberia", "unas"],
  },
  {
    id: "moda",
    label: "Moda y calzado",
    icon: TShirtIcon,
    color: "#7c3aed",
    emoji: "👗",
    categorias: ["ropa", "ropa_mujer", "ropa_hombre", "ropa_infantil", "ropa_deportiva", "lenceria", "uniformes", "calzado", "accesorios", "joyeria", "lentes_sol"],
  },
  {
    id: "hogar",
    label: "Hogar",
    icon: CouchIcon,
    color: "#b45309",
    emoji: "🛋️",
    categorias: ["hogar", "muebles", "decoracion", "electrodomesticos", "electro_pequeno", "blancos", "cocina", "ferreteria", "pintura", "jardineria", "limpieza"],
  },
  {
    id: "electronica",
    label: "Tecnología",
    icon: DeviceMobileIcon,
    color: "#475569",
    emoji: "📱",
    categorias: ["electronica", "celulares", "computadoras", "videojuegos", "audio", "camaras", "domotica"],
  },
  {
    id: "bebes",
    label: "Bebés y niños",
    icon: BabyIcon,
    color: "#f59e0b",
    emoji: "👶",
    categorias: ["bebes", "juguetes", "escolar_ninos", "sillas_auto"],
  },
  {
    id: "mascotas",
    label: "Mascotas",
    icon: PawPrintIcon,
    color: "#a16207",
    emoji: "🐾",
    categorias: ["mascotas", "veterinaria", "peluqueria_canina"],
  },
  {
    id: "papeleria",
    label: "Papelería y oficina",
    icon: PencilIcon,
    color: "#2563eb",
    emoji: "✏️",
    categorias: ["papeleria", "libreria", "oficina", "impresiones"],
  },
  {
    id: "deportes",
    label: "Deportes",
    icon: SoccerBallIcon,
    color: "#16a34a",
    emoji: "⚽",
    categorias: ["deportes", "suple_deportivo", "bicicletas", "gimnasio"],
  },
  {
    id: "automotriz",
    label: "Automotriz",
    icon: CarIcon,
    color: "#1e293b",
    emoji: "🚗",
    categorias: ["repuestos", "accesorios_auto", "lubricantes", "llantas", "lavado_autos", "motos"],
  },
  {
    id: "regalos",
    label: "Regalos y fiesta",
    icon: GiftIcon,
    color: "#dc2626",
    emoji: "🎁",
    categorias: ["flores", "regalos", "pinateria", "globos", "tarjetas", "peluches"],
  },
  {
    id: "construccion",
    label: "Construcción",
    icon: HardHatIcon,
    color: "#78716c",
    emoji: "🏗️",
    categorias: ["construccion", "herramientas", "electricidad_plomeria"],
  },
  {
    id: "hobbies",
    label: "Arte y entretenimiento",
    icon: PaintBrushIcon,
    color: "#d946ef",
    emoji: "🎨",
    categorias: ["instrumentos", "manualidades", "fotografia", "entretenimiento"],
  },
  {
    id: "servicios",
    label: "Servicios",
    icon: WrenchIcon,
    color: "#52525b",
    emoji: "🛠️",
    categorias: ["lavanderia", "mudanzas", "reparaciones", "cerrajeria"],
  },
  {
    id: "envios",
    label: "Envíos",
    icon: TruckIcon,
    color: "#6366f1",
    emoji: "🚚",
    categorias: ["envios"],
  },
  {
    id: "otros",
    label: "Otros",
    icon: PackageIcon,
    color: "#64748b",
    emoji: "📦",
    categorias: ["general", "segunda_mano", "importados", "religiosos", "souvenirs"],
  },
];

export function grupoDeCategoria(cat: string | undefined): CategoriaGrupo | undefined {
  const key = normalizarCategoria(cat);
  return CATEGORIA_GRUPOS.find((g) => g.categorias.includes(key));
}

/**
 * Algunas tiendas antiguas guardaron su categoría con mayúsculas (ej. "Comida" en vez de
 * "comida") desde un flujo previo a que se normalizara al enum de CATEGORIAS -- sin
 * normalizar aquí, esas tiendas caen siempre al ícono/color "general" por un simple
 * desajuste de mayúsculas, no porque de verdad no tengan categoría.
 */
function normalizarCategoria(cat: string | undefined): Categoria {
  return (cat?.toLowerCase() as Categoria) ?? "general";
}

export function categoriaIcon(cat: string | undefined): ComponentType<IconProps> {
  return CATEGORIA_ICON[normalizarCategoria(cat)] ?? PackageIcon;
}

export function categoriaColor(cat: string | undefined): string {
  return CATEGORIA_COLOR[normalizarCategoria(cat)] ?? CATEGORIA_COLOR.general;
}

export function categoriaEmoji(cat: string | undefined): string {
  return CATEGORIA_EMOJI[normalizarCategoria(cat)] ?? CATEGORIA_EMOJI.general;
}
