import { Avocado, Baby, BabyCarriage, Balloon, Barbell, Basket, Bed, BeerStein, Bicycle, Book, Bread, BowlFood, BowlSteam, Cake, Camera, Car, CarProfile, Carrot, Clipboard, Coffee, Confetti, Cookie, CookingPot, Couch, Cross, DeviceMobile, DeviceMobileCamera, Diamond, Dress, Drop, Egg, EggCrack, Envelope, Eyeglasses, Fire, FirstAid, FirstAidKit, Fish, FishSimple, Flame, Flower, ForkKnife, GameController, Gift, Globe, GraduationCap, Guitar, Hamburger, HandSoap, Handbag, HandsPraying, HardHat, Headphones, Heart, Heartbeat, IceCream, Key, Laptop, Leaf, Lightning, Motorcycle, NotePencil, OrangeSlice, Package, PaintBrush, PaintRoller, Palette, PawPrint, Pencil, Pill, Pizza, Plant, Plug, Plugs, Popcorn, PottedPlant, PuzzlePiece, Recycle, Scissors, ShirtFolded, Sneaker, SoccerBall, Sparkle, SprayBottle, Storefront, Sunglasses, TShirt, TeaBag, Ticket, Tire, Toolbox, Tooth, Truck, UsersThree, WashingMachine, Wheelchair, Wine, Wrench, type IconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";

export const CATEGORIAS = [
  "comida",
  "mercado",
  "farmacia",
  "bebidas",
  "panaderia",
  "postres",
  "frutas",
  "verduras",
  "ropa",
  "calzado",
  "electronica",
  "hogar",
  "envios",
  "general",
  "comida_rapida",
  "restaurantes",
  "comida_saludable",
  "vegana",
  "comida_tipica",
  "pizza",
  "sushi",
  "mexicana",
  "italiana",
  "pollo",
  "mariscos",
  "parrilla",
  "desayunos",
  "almuerzos",
  "catering",
  "dieta_especial",
  "cafe",
  "jugos",
  "cerveceria",
  "vinos",
  "energeticas",
  "te",
  "agua_refrescos",
  "reposteria",
  "heladeria",
  "chocolateria",
  "dulces_tipicos",
  "snacks",
  "carniceria",
  "pescaderia",
  "organicos",
  "granel",
  "lacteos",
  "huevos",
  "especias",
  "optica",
  "dental",
  "suplementos",
  "equipo_medico",
  "adulto_mayor",
  "primeros_auxilios",
  "cosmeticos",
  "cuidado_piel",
  "peluqueria",
  "perfumeria",
  "higiene",
  "barberia",
  "unas",
  "ropa_mujer",
  "ropa_hombre",
  "ropa_infantil",
  "ropa_deportiva",
  "lenceria",
  "uniformes",
  "accesorios",
  "joyeria",
  "lentes_sol",
  "muebles",
  "decoracion",
  "electrodomesticos",
  "electro_pequeno",
  "blancos",
  "cocina",
  "ferreteria",
  "pintura",
  "jardineria",
  "limpieza",
  "celulares",
  "computadoras",
  "videojuegos",
  "audio",
  "camaras",
  "domotica",
  "bebes",
  "juguetes",
  "escolar_ninos",
  "sillas_auto",
  "mascotas",
  "veterinaria",
  "peluqueria_canina",
  "papeleria",
  "libreria",
  "oficina",
  "impresiones",
  "deportes",
  "suple_deportivo",
  "bicicletas",
  "gimnasio",
  "repuestos",
  "accesorios_auto",
  "lubricantes",
  "llantas",
  "lavado_autos",
  "motos",
  "flores",
  "regalos",
  "pinateria",
  "globos",
  "tarjetas",
  "peluches",
  "construccion",
  "herramientas",
  "electricidad_plomeria",
  "instrumentos",
  "manualidades",
  "fotografia",
  "entretenimiento",
  "lavanderia",
  "mudanzas",
  "reparaciones",
  "cerrajeria",
  "segunda_mano",
  "importados",
  "religiosos",
  "souvenirs",
] as const;
export type Categoria = (typeof CATEGORIAS)[number];

export const CATEGORIA_LABEL: Record<Categoria, string> = {
  comida: "Comida",
  mercado: "Mercado",
  farmacia: "Farmacia",
  bebidas: "Bebidas",
  panaderia: "Panadería",
  postres: "Postres",
  frutas: "Frutas",
  verduras: "Verduras",
  ropa: "Ropa",
  calzado: "Calzado",
  electronica: "Electrónica",
  hogar: "Hogar",
  envios: "Envíos",
  general: "General",
  comida_rapida: "Comida rápida",
  restaurantes: "Restaurantes",
  comida_saludable: "Comida saludable",
  vegana: "Vegana/vegetariana",
  comida_tipica: "Comida típica",
  pizza: "Pizza",
  sushi: "Sushi/asiática",
  mexicana: "Comida mexicana",
  italiana: "Comida italiana",
  pollo: "Pollo/rostizados",
  mariscos: "Mariscos",
  parrilla: "Parrilladas/carnes",
  desayunos: "Desayunos",
  almuerzos: "Almuerzos ejecutivos",
  catering: "Catering/eventos",
  dieta_especial: "Dietas especiales",
  cafe: "Café",
  jugos: "Jugos naturales",
  cerveceria: "Cervecería",
  vinos: "Vinos y licores",
  energeticas: "Bebidas energéticas",
  te: "Té/infusiones",
  agua_refrescos: "Agua y refrescos",
  reposteria: "Repostería/pasteles",
  heladeria: "Heladería",
  chocolateria: "Chocolatería",
  dulces_tipicos: "Dulces típicos",
  snacks: "Snacks/botanas",
  carniceria: "Carnicería",
  pescaderia: "Pescadería",
  organicos: "Productos orgánicos",
  granel: "Productos a granel",
  lacteos: "Lácteos",
  huevos: "Huevos",
  especias: "Especias y condimentos",
  optica: "Óptica",
  dental: "Dental",
  suplementos: "Suplementos/vitaminas",
  equipo_medico: "Equipo médico",
  adulto_mayor: "Adultos mayores",
  primeros_auxilios: "Primeros auxilios",
  cosmeticos: "Cosméticos/maquillaje",
  cuidado_piel: "Cuidado de la piel",
  peluqueria: "Peluquería",
  perfumeria: "Perfumería",
  higiene: "Higiene personal",
  barberia: "Barbería",
  unas: "Uñas/manicure",
  ropa_mujer: "Ropa de mujer",
  ropa_hombre: "Ropa de hombre",
  ropa_infantil: "Ropa infantil",
  ropa_deportiva: "Ropa deportiva",
  lenceria: "Ropa íntima",
  uniformes: "Uniformes",
  accesorios: "Accesorios",
  joyeria: "Joyería y relojes",
  lentes_sol: "Lentes de sol",
  muebles: "Muebles",
  decoracion: "Decoración",
  electrodomesticos: "Electrodomésticos",
  electro_pequeno: "Electrodomésticos pequeños",
  blancos: "Blancos (sábanas/toallas)",
  cocina: "Cocina y utensilios",
  ferreteria: "Ferretería",
  pintura: "Pintura",
  jardineria: "Jardinería/plantas",
  limpieza: "Productos de limpieza",
  celulares: "Celulares y accesorios",
  computadoras: "Computadoras/laptops",
  videojuegos: "Videojuegos",
  audio: "Audio/parlantes",
  camaras: "Cámaras",
  domotica: "Domótica",
  bebes: "Artículos para bebé",
  juguetes: "Juguetes",
  escolar_ninos: "Escolares",
  sillas_auto: "Coches/sillas de carro",
  mascotas: "Mascotas",
  veterinaria: "Veterinaria",
  peluqueria_canina: "Peluquería canina",
  papeleria: "Papelería/útiles",
  libreria: "Librería/libros",
  oficina: "Material de oficina",
  impresiones: "Impresiones/copias",
  deportes: "Artículos deportivos",
  suple_deportivo: "Suplementos deportivos",
  bicicletas: "Bicicletas",
  gimnasio: "Equipo de gimnasio",
  repuestos: "Repuestos",
  accesorios_auto: "Accesorios para vehículos",
  lubricantes: "Lubricantes",
  llantas: "Llantas",
  lavado_autos: "Lavado de autos",
  motos: "Motocicletas",
  flores: "Flores/florería",
  regalos: "Regalos",
  pinateria: "Piñatería/fiesta",
  globos: "Globos",
  tarjetas: "Tarjetas y envoltorios",
  peluches: "Peluches",
  construccion: "Materiales de construcción",
  herramientas: "Herramientas",
  electricidad_plomeria: "Electricidad/plomería",
  instrumentos: "Instrumentos musicales",
  manualidades: "Arte/manualidades",
  fotografia: "Fotografía",
  entretenimiento: "Boletos/entretenimiento",
  lavanderia: "Lavandería",
  mudanzas: "Mudanzas",
  reparaciones: "Reparaciones a domicilio",
  cerrajeria: "Cerrajería",
  segunda_mano: "Segunda mano/usado",
  importados: "Importados",
  religiosos: "Artículos religiosos",
  souvenirs: "Souvenirs/artesanías",
};

export const CATEGORIA_ICON: Record<Categoria, ComponentType<IconProps>> = {
  comida: ForkKnife,
  mercado: Basket,
  farmacia: Pill,
  bebidas: Coffee,
  panaderia: Bread,
  postres: IceCream,
  frutas: Leaf,
  verduras: Carrot,
  ropa: TShirt,
  calzado: Sneaker,
  electronica: DeviceMobile,
  hogar: Couch,
  envios: Truck,
  general: Package,
  comida_rapida: Hamburger,
  restaurantes: Storefront,
  comida_saludable: Avocado,
  vegana: Plant,
  comida_tipica: BowlFood,
  pizza: Pizza,
  sushi: FishSimple,
  mexicana: CookingPot,
  italiana: BowlSteam,
  pollo: Fire,
  mariscos: Fish,
  parrilla: Flame,
  desayunos: Egg,
  almuerzos: Package,
  catering: UsersThree,
  dieta_especial: Heartbeat,
  cafe: Coffee,
  jugos: OrangeSlice,
  cerveceria: BeerStein,
  vinos: Wine,
  energeticas: Lightning,
  te: TeaBag,
  agua_refrescos: Drop,
  reposteria: Cake,
  heladeria: IceCream,
  chocolateria: Cookie,
  dulces_tipicos: Cookie,
  snacks: Popcorn,
  carniceria: Fire,
  pescaderia: Fish,
  organicos: Plant,
  granel: Basket,
  lacteos: Drop,
  huevos: EggCrack,
  especias: Fire,
  optica: Eyeglasses,
  dental: Tooth,
  suplementos: Pill,
  equipo_medico: FirstAidKit,
  adulto_mayor: Wheelchair,
  primeros_auxilios: FirstAid,
  cosmeticos: Sparkle,
  cuidado_piel: Drop,
  peluqueria: Scissors,
  perfumeria: Flower,
  higiene: HandSoap,
  barberia: Scissors,
  unas: Sparkle,
  ropa_mujer: Dress,
  ropa_hombre: TShirt,
  ropa_infantil: Baby,
  ropa_deportiva: Barbell,
  lenceria: Heart,
  uniformes: ShirtFolded,
  accesorios: Handbag,
  joyeria: Diamond,
  lentes_sol: Sunglasses,
  muebles: Couch,
  decoracion: Palette,
  electrodomesticos: WashingMachine,
  electro_pequeno: Plug,
  blancos: Bed,
  cocina: CookingPot,
  ferreteria: Wrench,
  pintura: PaintRoller,
  jardineria: PottedPlant,
  limpieza: SprayBottle,
  celulares: DeviceMobileCamera,
  computadoras: Laptop,
  videojuegos: GameController,
  audio: Headphones,
  camaras: Camera,
  domotica: Plugs,
  bebes: Baby,
  juguetes: PuzzlePiece,
  escolar_ninos: GraduationCap,
  sillas_auto: BabyCarriage,
  mascotas: PawPrint,
  veterinaria: Cross,
  peluqueria_canina: Scissors,
  papeleria: Pencil,
  libreria: Book,
  oficina: Clipboard,
  impresiones: NotePencil,
  deportes: SoccerBall,
  suple_deportivo: Barbell,
  bicicletas: Bicycle,
  gimnasio: Barbell,
  repuestos: CarProfile,
  accesorios_auto: Car,
  lubricantes: Drop,
  llantas: Tire,
  lavado_autos: SprayBottle,
  motos: Motorcycle,
  flores: Flower,
  regalos: Gift,
  pinateria: Confetti,
  globos: Balloon,
  tarjetas: Envelope,
  peluches: PuzzlePiece,
  construccion: HardHat,
  herramientas: Toolbox,
  electricidad_plomeria: Plug,
  instrumentos: Guitar,
  manualidades: PaintBrush,
  fotografia: Camera,
  entretenimiento: Ticket,
  lavanderia: WashingMachine,
  mudanzas: Truck,
  reparaciones: Wrench,
  cerrajeria: Key,
  segunda_mano: Recycle,
  importados: Globe,
  religiosos: HandsPraying,
  souvenirs: Package,
};

/** One accent hue per category so the category rail isn't monochrome. */
export const CATEGORIA_COLOR: Record<Categoria, string> = {
  comida: "#f97316",
  mercado: "#10b981",
  farmacia: "#14b8a6",
  bebidas: "#3b82f6",
  panaderia: "#d97706",
  postres: "#ec4899",
  frutas: "#84cc16",
  verduras: "#15803d",
  ropa: "#7c3aed",
  calzado: "#0891b2",
  electronica: "#475569",
  hogar: "#b45309",
  envios: "#6366f1",
  general: "#64748b",
  comida_rapida: "#ea580c",
  restaurantes: "#b91c1c",
  comida_saludable: "#16a34a",
  vegana: "#15803d",
  comida_tipica: "#b45309",
  pizza: "#dc2626",
  sushi: "#db2777",
  mexicana: "#ea580c",
  italiana: "#ca8a04",
  pollo: "#d97706",
  mariscos: "#0891b2",
  parrilla: "#dc2626",
  desayunos: "#f59e0b",
  almuerzos: "#78716c",
  catering: "#7c3aed",
  dieta_especial: "#059669",
  cafe: "#78350f",
  jugos: "#f97316",
  cerveceria: "#ca8a04",
  vinos: "#7c2d12",
  energeticas: "#eab308",
  te: "#65a30d",
  agua_refrescos: "#0ea5e9",
  reposteria: "#ec4899",
  heladeria: "#38bdf8",
  chocolateria: "#78350f",
  dulces_tipicos: "#f472b6",
  snacks: "#eab308",
  carniceria: "#b91c1c",
  pescaderia: "#0284c7",
  organicos: "#22c55e",
  granel: "#a16207",
  lacteos: "#64748b",
  huevos: "#ca8a04",
  especias: "#dc2626",
  optica: "#0891b2",
  dental: "#06b6d4",
  suplementos: "#16a34a",
  equipo_medico: "#dc2626",
  adulto_mayor: "#6366f1",
  primeros_auxilios: "#ef4444",
  cosmeticos: "#ec4899",
  cuidado_piel: "#f472b6",
  peluqueria: "#a855f7",
  perfumeria: "#d946ef",
  higiene: "#06b6d4",
  barberia: "#1e293b",
  unas: "#f43f5e",
  ropa_mujer: "#db2777",
  ropa_hombre: "#2563eb",
  ropa_infantil: "#f59e0b",
  ropa_deportiva: "#16a34a",
  lenceria: "#f43f5e",
  uniformes: "#475569",
  accesorios: "#a16207",
  joyeria: "#eab308",
  lentes_sol: "#1e293b",
  muebles: "#92400e",
  decoracion: "#d946ef",
  electrodomesticos: "#64748b",
  electro_pequeno: "#0891b2",
  blancos: "#3b82f6",
  cocina: "#ea580c",
  ferreteria: "#52525b",
  pintura: "#dc2626",
  jardineria: "#16a34a",
  limpieza: "#06b6d4",
  celulares: "#2563eb",
  computadoras: "#1e293b",
  videojuegos: "#7c3aed",
  audio: "#ea580c",
  camaras: "#0f172a",
  domotica: "#eab308",
  bebes: "#ec4899",
  juguetes: "#f59e0b",
  escolar_ninos: "#2563eb",
  sillas_auto: "#16a34a",
  mascotas: "#a16207",
  veterinaria: "#dc2626",
  peluqueria_canina: "#0891b2",
  papeleria: "#2563eb",
  libreria: "#78350f",
  oficina: "#475569",
  impresiones: "#64748b",
  deportes: "#16a34a",
  suple_deportivo: "#dc2626",
  bicicletas: "#0891b2",
  gimnasio: "#7c3aed",
  repuestos: "#475569",
  accesorios_auto: "#1e293b",
  lubricantes: "#78350f",
  llantas: "#27272a",
  lavado_autos: "#0ea5e9",
  motos: "#dc2626",
  flores: "#ec4899",
  regalos: "#dc2626",
  pinateria: "#f59e0b",
  globos: "#a855f7",
  tarjetas: "#ec4899",
  peluches: "#f472b6",
  construccion: "#f59e0b",
  herramientas: "#52525b",
  electricidad_plomeria: "#eab308",
  instrumentos: "#7c2d12",
  manualidades: "#d946ef",
  fotografia: "#1e293b",
  entretenimiento: "#7c3aed",
  lavanderia: "#0891b2",
  mudanzas: "#78716c",
  reparaciones: "#ca8a04",
  cerrajeria: "#52525b",
  segunda_mano: "#16a34a",
  importados: "#2563eb",
  religiosos: "#a16207",
  souvenirs: "#ea580c",
};

/**
 * Native emoji glyphs, used only for the Home category rail's big glossy
 * icons. The system emoji font (Segoe UI Emoji on Windows 11, Apple/Noto
 * elsewhere) is rendered as shaded 3D art by the OS itself -- the closest
 * thing to a licensed 3D icon pack available without adding one.
 */
export const CATEGORIA_EMOJI: Record<Categoria, string> = {
  comida: "🍔",
  mercado: "🛒",
  farmacia: "💊",
  bebidas: "🥤",
  panaderia: "🍞",
  postres: "🍰",
  frutas: "🍎",
  verduras: "🥕",
  ropa: "👕",
  calzado: "👟",
  electronica: "📱",
  hogar: "🛋️",
  envios: "🚚",
  general: "📦",
  comida_rapida: "🍔",
  restaurantes: "🍽️",
  comida_saludable: "🥑",
  vegana: "🌱",
  comida_tipica: "🫓",
  pizza: "🍕",
  sushi: "🍣",
  mexicana: "🌮",
  italiana: "🍝",
  pollo: "🍗",
  mariscos: "🦐",
  parrilla: "🥩",
  desayunos: "🍳",
  almuerzos: "🍱",
  catering: "🥂",
  dieta_especial: "💚",
  cafe: "☕",
  jugos: "🧃",
  cerveceria: "🍺",
  vinos: "🍷",
  energeticas: "⚡",
  te: "🍵",
  agua_refrescos: "🥤",
  reposteria: "🎂",
  heladeria: "🍦",
  chocolateria: "🍫",
  dulces_tipicos: "🍬",
  snacks: "🍿",
  carniceria: "🥩",
  pescaderia: "🐟",
  organicos: "🌿",
  granel: "🌾",
  lacteos: "🥛",
  huevos: "🥚",
  especias: "🌶️",
  optica: "👓",
  dental: "🦷",
  suplementos: "💊",
  equipo_medico: "🩺",
  adulto_mayor: "🧓",
  primeros_auxilios: "🚑",
  cosmeticos: "💄",
  cuidado_piel: "🧴",
  peluqueria: "💇",
  perfumeria: "🌸",
  higiene: "🧼",
  barberia: "💈",
  unas: "💅",
  ropa_mujer: "👗",
  ropa_hombre: "👔",
  ropa_infantil: "🧒",
  ropa_deportiva: "🎽",
  lenceria: "👙",
  uniformes: "🥼",
  accesorios: "👜",
  joyeria: "💍",
  lentes_sol: "🕶️",
  muebles: "🛋️",
  decoracion: "🖼️",
  electrodomesticos: "🧺",
  electro_pequeno: "🔌",
  blancos: "🛏️",
  cocina: "🍳",
  ferreteria: "🔧",
  pintura: "🎨",
  jardineria: "🪴",
  limpieza: "🧽",
  celulares: "📱",
  computadoras: "💻",
  videojuegos: "🎮",
  audio: "🎧",
  camaras: "📷",
  domotica: "💡",
  bebes: "👶",
  juguetes: "🧸",
  escolar_ninos: "🎒",
  sillas_auto: "🍼",
  mascotas: "🐾",
  veterinaria: "🐶",
  peluqueria_canina: "🐩",
  papeleria: "✏️",
  libreria: "📚",
  oficina: "🗂️",
  impresiones: "🖨️",
  deportes: "⚽",
  suple_deportivo: "🏋️",
  bicicletas: "🚲",
  gimnasio: "🏋️‍♂️",
  repuestos: "🔩",
  accesorios_auto: "🚗",
  lubricantes: "🛢️",
  llantas: "🛞",
  lavado_autos: "🚿",
  motos: "🏍️",
  flores: "💐",
  regalos: "🎁",
  pinateria: "🎉",
  globos: "🎈",
  tarjetas: "💌",
  peluches: "🧸",
  construccion: "🏗️",
  herramientas: "🧰",
  electricidad_plomeria: "⚡",
  instrumentos: "🎸",
  manualidades: "🖌️",
  fotografia: "📸",
  entretenimiento: "🎟️",
  lavanderia: "🧺",
  mudanzas: "🚚",
  reparaciones: "🛠️",
  cerrajeria: "🔑",
  segunda_mano: "♻️",
  importados: "🌎",
  religiosos: "🙏",
  souvenirs: "🎁",
};

export interface CategoriaGrupo {
  id: string;
  label: string;
  icon: ComponentType<IconProps>;
  color: string;
  emoji: string;
  categorias: Categoria[];
}

/**
 * Agrupa las 129 categorías en ~20 "familias" principales para la barra de Inicio y el
 * primer nivel de filtros de Explorar -- mostrar las 129 sueltas obliga a deslizar una
 * lista larguísima; agrupadas, cada familia expande sus categorías específicas bajo
 * demanda (segundo nivel de chips en Explorar).
 */
export const CATEGORIA_GRUPOS: CategoriaGrupo[] = [
  {
    id: "comida",
    label: "Comida",
    icon: ForkKnife,
    color: "#f97316",
    emoji: "🍔",
    categorias: ["comida", "comida_rapida", "restaurantes", "comida_saludable", "vegana", "comida_tipica", "pizza", "sushi", "mexicana", "italiana", "pollo", "mariscos", "parrilla", "desayunos", "almuerzos", "catering", "dieta_especial"],
  },
  {
    id: "mercado",
    label: "Mercado",
    icon: Basket,
    color: "#10b981",
    emoji: "🛒",
    categorias: ["mercado", "carniceria", "pescaderia", "organicos", "granel", "lacteos", "huevos", "especias", "snacks"],
  },
  {
    id: "panaderia",
    label: "Panadería y postres",
    icon: Bread,
    color: "#d97706",
    emoji: "🍞",
    categorias: ["panaderia", "postres", "reposteria", "heladeria", "chocolateria", "dulces_tipicos"],
  },
  {
    id: "frutas",
    label: "Frutas y verduras",
    icon: Carrot,
    color: "#84cc16",
    emoji: "🍎",
    categorias: ["frutas", "verduras"],
  },
  {
    id: "bebidas",
    label: "Bebidas",
    icon: Coffee,
    color: "#3b82f6",
    emoji: "🥤",
    categorias: ["bebidas", "cafe", "jugos", "cerveceria", "vinos", "energeticas", "te", "agua_refrescos"],
  },
  {
    id: "farmacia",
    label: "Farmacia y salud",
    icon: Pill,
    color: "#14b8a6",
    emoji: "💊",
    categorias: ["farmacia", "optica", "dental", "suplementos", "equipo_medico", "adulto_mayor", "primeros_auxilios"],
  },
  {
    id: "belleza",
    label: "Belleza y cuidado",
    icon: Sparkle,
    color: "#ec4899",
    emoji: "💄",
    categorias: ["cosmeticos", "cuidado_piel", "peluqueria", "perfumeria", "higiene", "barberia", "unas"],
  },
  {
    id: "moda",
    label: "Moda y calzado",
    icon: TShirt,
    color: "#7c3aed",
    emoji: "👗",
    categorias: ["ropa", "ropa_mujer", "ropa_hombre", "ropa_infantil", "ropa_deportiva", "lenceria", "uniformes", "calzado", "accesorios", "joyeria", "lentes_sol"],
  },
  {
    id: "hogar",
    label: "Hogar",
    icon: Couch,
    color: "#b45309",
    emoji: "🛋️",
    categorias: ["hogar", "muebles", "decoracion", "electrodomesticos", "electro_pequeno", "blancos", "cocina", "ferreteria", "pintura", "jardineria", "limpieza"],
  },
  {
    id: "electronica",
    label: "Tecnología",
    icon: DeviceMobile,
    color: "#475569",
    emoji: "📱",
    categorias: ["electronica", "celulares", "computadoras", "videojuegos", "audio", "camaras", "domotica"],
  },
  {
    id: "bebes",
    label: "Bebés y niños",
    icon: Baby,
    color: "#f59e0b",
    emoji: "👶",
    categorias: ["bebes", "juguetes", "escolar_ninos", "sillas_auto"],
  },
  {
    id: "mascotas",
    label: "Mascotas",
    icon: PawPrint,
    color: "#a16207",
    emoji: "🐾",
    categorias: ["mascotas", "veterinaria", "peluqueria_canina"],
  },
  {
    id: "papeleria",
    label: "Papelería y oficina",
    icon: Pencil,
    color: "#2563eb",
    emoji: "✏️",
    categorias: ["papeleria", "libreria", "oficina", "impresiones"],
  },
  {
    id: "deportes",
    label: "Deportes",
    icon: SoccerBall,
    color: "#16a34a",
    emoji: "⚽",
    categorias: ["deportes", "suple_deportivo", "bicicletas", "gimnasio"],
  },
  {
    id: "automotriz",
    label: "Automotriz",
    icon: Car,
    color: "#1e293b",
    emoji: "🚗",
    categorias: ["repuestos", "accesorios_auto", "lubricantes", "llantas", "lavado_autos", "motos"],
  },
  {
    id: "regalos",
    label: "Regalos y fiesta",
    icon: Gift,
    color: "#dc2626",
    emoji: "🎁",
    categorias: ["flores", "regalos", "pinateria", "globos", "tarjetas", "peluches"],
  },
  {
    id: "construccion",
    label: "Construcción",
    icon: HardHat,
    color: "#78716c",
    emoji: "🏗️",
    categorias: ["construccion", "herramientas", "electricidad_plomeria"],
  },
  {
    id: "hobbies",
    label: "Arte y entretenimiento",
    icon: PaintBrush,
    color: "#d946ef",
    emoji: "🎨",
    categorias: ["instrumentos", "manualidades", "fotografia", "entretenimiento"],
  },
  {
    id: "servicios",
    label: "Servicios",
    icon: Wrench,
    color: "#52525b",
    emoji: "🛠️",
    categorias: ["lavanderia", "mudanzas", "reparaciones", "cerrajeria"],
  },
  {
    id: "envios",
    label: "Envíos",
    icon: Truck,
    color: "#6366f1",
    emoji: "🚚",
    categorias: ["envios"],
  },
  {
    id: "otros",
    label: "Otros",
    icon: Package,
    color: "#64748b",
    emoji: "📦",
    categorias: ["general", "segunda_mano", "importados", "religiosos", "souvenirs"],
  },
];

export function grupoDeCategoria(cat: string | undefined): CategoriaGrupo | undefined {
  const key = normalizarCategoria(cat);
  return CATEGORIA_GRUPOS.find((g) => g.categorias.includes(key));
}

/**
 * Algunas tiendas antiguas guardaron su categoría con mayúsculas (ej. "Comida" en vez de
 * "comida") desde un flujo previo a que se normalizara al enum de CATEGORIAS -- sin
 * normalizar aquí, esas tiendas caen siempre al ícono/color "general" por un simple
 * desajuste de mayúsculas, no porque de verdad no tengan categoría.
 */
function normalizarCategoria(cat: string | undefined): Categoria {
  return (cat?.toLowerCase() as Categoria) ?? "general";
}

export function categoriaIcon(cat: string | undefined): ComponentType<IconProps> {
  return CATEGORIA_ICON[normalizarCategoria(cat)] ?? Package;
}

export function categoriaColor(cat: string | undefined): string {
  return CATEGORIA_COLOR[normalizarCategoria(cat)] ?? CATEGORIA_COLOR.general;
}

export function categoriaEmoji(cat: string | undefined): string {
  return CATEGORIA_EMOJI[normalizarCategoria(cat)] ?? CATEGORIA_EMOJI.general;
}
