// src/screens/Chat/styles.ts
import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14 },
  headerTitle: { fontSize: 22, fontWeight: '900', color: '#111' },
  newChatBtn: { backgroundColor: '#f3f4f6', borderRadius: 12, padding: 8 },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f3f4f6', marginHorizontal: 16, marginBottom: 8, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 10 },
  searchInput: { flex: 1, fontSize: 14, color: '#111' },
  chatItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', gap: 12 },
  chatAvatarWrap: { position: 'relative' },
  listAvatar: { width: 52, height: 52, borderRadius: 999 },
  onlineDotList: { position: 'absolute', bottom: 2, right: 2, width: 12, height: 12, borderRadius: 999, backgroundColor: '#10b981', borderWidth: 2, borderColor: '#fff' },
  chatItemHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  chatItemName: { fontSize: 15, fontWeight: '800', color: '#111' },
  chatItemTime: { fontSize: 11, color: '#9ca3af' },
  chatItemBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 2 },
  chatItemMsg: { fontSize: 13, color: '#6b7280', flex: 1 },
  unreadBadge: { backgroundColor: '#059669', borderRadius: 999, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  unreadTxt: { color: '#fff', fontSize: 10, fontWeight: '900' },
  chatItemStatus: { fontSize: 11, marginTop: 2, fontWeight: '600' },
  chatHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', gap: 10 },
  backBtn: { padding: 4 },
  chatHeaderAvatar: { position: 'relative' },
  chatAvatar: { width: 40, height: 40, borderRadius: 999 },
  onlineDot: { position: 'absolute', bottom: 0, right: 0, width: 10, height: 10, borderRadius: 999, borderWidth: 2, borderColor: '#fff' },
  chatHeaderName: { fontSize: 15, fontWeight: '800', color: '#111' },
  chatHeaderStatus: { fontSize: 11, fontWeight: '600' },
  chatAction: { padding: 8 },
  trackingBanner: { backgroundColor: '#f0fdf4', padding: 12, borderBottomWidth: 1, borderBottomColor: '#dcfce7' },
  trackingTitle: { fontSize: 13, fontWeight: '800', color: '#059669', marginBottom: 8 },
  trackingSteps: { flexDirection: 'row', justifyContent: 'space-between' },
  trackingStep: { alignItems: 'center', gap: 4 },
  trackingDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: '#d1d5db' },
  trackingDotActive: { backgroundColor: '#059669' },
  trackingStepTxt: { fontSize: 9, color: '#9ca3af', fontWeight: '600' },
  trackingStepActive: { color: '#059669' },
  msgRow: { flexDirection: 'row', justifyContent: 'flex-start', marginBottom: 4 },
  msgRowMe: { justifyContent: 'flex-end' },
  bubble: { maxWidth: '75%', borderRadius: 18, padding: 12 },
  bubbleMe: { backgroundColor: '#059669', borderBottomRightRadius: 4 },
  bubbleThem: { backgroundColor: '#f3f4f6', borderBottomLeftRadius: 4 },
  bubbleTxt: { fontSize: 14, color: '#111', lineHeight: 20 },
  bubbleTime: { fontSize: 10, color: '#9ca3af', marginTop: 4, textAlign: 'right' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#f3f4f6', gap: 8 },
  attachBtn: { padding: 8 },
  msgInput: { flex: 1, backgroundColor: '#f3f4f6', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 10, fontSize: 14, color: '#111', maxHeight: 100 },
  sendBtn: { backgroundColor: '#059669', width: 40, height: 40, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
});